sudo: required
language: generic

services:
  - docker

git:
  depth: 3

env:
  - PROFILE=.profile VIM=vim    TAG=latest
  - PROFILE=.profile VIM=vim    TAG=v8.0.0107
  - PROFILE=.profile VIM=vim    TAG=v8.1.0000
  - PROFILE=.profile VIM=vim    TAG=v8.1.0342
  - PROFILE=.profile VIM=vim    TAG=v8.1.0349
  - PROFILE=.profile VIM=vim    TAG=v8.1.0367
  - PROFILE=.profile VIM=neovim TAG=latest
  - PROFILE=.profile VIM=neovim TAG=v0.2.0
  - PROFILE=.profile VIM=neovim TAG=v0.2.1
  - PROFILE=.profile VIM=neovim TAG=v0.2.2
  - PROFILE=.profile VIM=neovim TAG=v0.3.0
  - PROFILE=.profile VIM=neovim TAG=v0.3.1


addons:
  apt:
    packages:
      - docker-ce
      - python3
      - python3-pip

install:
  - pip3 install --user setuptools --upgrade
  - pip3 install --user vim-vint typing
  - pip3 install --user coverage covimerage
  - docker --version
  - make VIM=${VIM} TAG=${TAG} image

before_script:
  - uname -a
  - python3 --version
  - vint --version
  - make VIM=${VIM} TAG=${TAG} version

script:
  - vint autoload/gina autoload/vital/__gina__ plugin ftplugin
  - make VIM=${VIM} TAG=${TAG} ARGS="-e PROFILE=${PROFILE} -e CI=docker" test
  - make VIM=${VIM} TAG=${TAG} helptags

after_success:
  - covimerage write_coverage $PROFILE
  - coverage xml
  - bash <(curl -s https://codecov.io/bash)
