language: generic
git:
  depth: 3

os:
  #- linux
  - osx
env:
  #- PYTHON=0 VIM=vim  VIM_VERSION=HEAD
  #- PYTHON=0 VIM=vim  VIM_VERSION=v8.0.0027
  #- PYTHON=2 VIM=vim  VIM_VERSION=HEAD
  #- PYTHON=2 VIM=vim  VIM_VERSION=v8.0.0027
  #- PYTHON=3 VIM=vim  VIM_VERSION=HEAD
  #- PYTHON=3 VIM=vim  VIM_VERSION=v8.0.0027
  #- PYTHON=0 VIM=nvim VIM_VERSION=HEAD   THEMIS_ARGS="-e -s --headless"
  #- PYTHON=0 VIM=nvim VIM_VERSION=v0.1.7 THEMIS_ARGS="-e -s --headless"
  #- PYTHON=2 VIM=nvim VIM_VERSION=HEAD   THEMIS_ARGS="-e -s --headless"
  - PYTHON=2 VIM=nvim VIM_VERSION=v0.1.7 THEMIS_ARGS="-e -s --headless"
  #- PYTHON=3 VIM=nvim VIM_VERSION=HEAD   THEMIS_ARGS="-e -s --headless"
  - PYTHON=3 VIM=nvim VIM_VERSION=v0.1.7 THEMIS_ARGS="-e -s --headless"

cache:
  - directories:
    - $HOME/cache
    - $HOME/themis
    - $HOME/.cache/pip
    - $HOME/Library/Caches/Homebrew
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

addons:
  apt:
    packages:
      - gettext
      - libncurses5-dev
      - libacl1-dev
      - libgpm-dev
      - python-dev
      - python3-dev
      - python3-setuptools
      - lua5.2
      - liblua5.2-dev

install:
  - git config --global user.name "ci"
  - git config --global user.email ci@example.com
  - export PYTHONUSERBASE="$HOME/.local"  # Override it for OS X
  - OS_NAME=${TRAVIS_OS_NAME} .ci/install.sh
  - export PATH="$HOME/vim/bin:$HOME/themis/bin:$PATH"
  - export THEMIS_HOME=$HOME/themis
  - export THEMIS_VIM=$VIM

before_script:
  - echo $PATH
  - echo $THEMIS_HOME
  - echo $THEMIS_VIM
  - echo $THEMIS_ARGS
  - uname -a
  - which -a python
  - python --version
  - which -a python3
  - python3 --version
  - which -a $VIM
  - $VIM --version
  - which -a vint
  - vint --version
  - which -a themis
  - themis --version

script:
  - vint autoload/gina autoload/vital/__gina__ plugin ftplugin
  - themis --reporter dot
  - $THEMIS_VIM --cmd "try | helptags doc/ | catch | cquit | endtry" --cmd quit
