sudo: required
language: generic

services:
  - docker

git:
  depth: 3

env:
  - PROFILE=.profile VIM=vim    TAG=latest
  - PROFILE=.profile VIM=vim    TAG=v8.0.0107
  - PROFILE=.profile VIM=vim    TAG=v8.1.0000
  - PROFILE=.profile VIM=vim    TAG=v8.1.2000
  - PROFILE=.profile VIM=neovim TAG=latest
  - PROFILE=.profile VIM=neovim TAG=v0.3.0
  - PROFILE=.profile VIM=neovim TAG=v0.4.0
  - PROFILE=.profile VIM=neovim TAG=v0.4.2


addons:
  apt:
    packages:
      - docker-ce
      - python3
      - python3-pip

install:
  - pip3 install --user setuptools --upgrade
  - pip3 install --user coverage covimerage
  - docker --version
  - make VIM=${VIM} TAG=${TAG} image

before_script:
  - uname -a
  - python3 --version
  - make VIM=${VIM} TAG=${TAG} version

script:
  - make VIM=${VIM} TAG=${TAG} ARGS="-e PROFILE=${PROFILE} -e CI=docker" test
  - make VIM=${VIM} TAG=${TAG} helptags

after_success:
  - covimerage write_coverage $PROFILE
  - coverage xml
  - bash <(curl -s https://codecov.io/bash)
