sudo: required
language: generic

services:
  - docker

git:
  depth: 3

env:
  - PROFILE=.profile VIM=vim    TAG=latest
  - PROFILE=.profile VIM=vim    TAG=v8.0.0027
  - PROFILE=.profile VIM=neovim TAG=latest
  - PROFILE=.profile VIM=neovim TAG=v0.2.0
  - PROFILE=.profile VIM=neovim TAG=v0.2.2


addons:
  apt:
    packages:
      - python3
      - python3-pip

install:
  - pip3 install setuptools --upgrade
  - pip3 install vim-vint
  - pip3 install coverage covimerage
  - docker build -t ci-test --build-arg TAG=${TAG} -f .ci/Dockerfile.${VIM} .

before_script:
  - uname -a
  - python3 --version
  - vint --version
  - docker run --rm -it ci-test --version
  - docker run --rm -it lambdalisue/${VIM}-ci:${TAG} --version

script:
  - vint autoload/gina autoload/vital/__gina__ plugin ftplugin
  - docker run --rm --volume ${PWD}:/mnt/volume -e "PROFILE=${PROFILE}" -it ci-test
  - docker run --rm --volume ${PWD}:/mnt/volume -it lambdalisue/${VIM}-ci:${TAG} --cmd "try | helptags doc/ | catch | cquit | endtry" --cmd quit

after_success:
  - covimerage write_coverage $PROFILE
  - coverage xml
  - bash <(curl -s https://codecov.io/bash)
